### PR TITLE
Made it work on repositories with spaces in their names.

### PR DESCRIPTION
**Pull request by svspire**
Fixed output message for superstatus.

### CODE REVIEW

**Comment by JKrag** [comment]
Hi Shannon. 
Thanks for the PR. I have merged it in, without further testing, as I don't currently use Mercurial, and the changes looked quite safe and complete. :-D
For the same reason I would be happy to add you as a collaborator to the repo if you have more to contribute. Just let me know.
BR Jan

**Comment by svspire** [comment]
Jan-

I don't have any more to contribute at the moment, but thanks. This has been a very handy script for me.

I expect I'll be looking for something like this for git in the near future. It has probably already been done, but if not I might try to modify this script to do the job.

Cheers,
Shannon

**Comment by JKrag** [comment]
Hi Shannon.
Look no further :-)
https://github.com/JKrag/gitall (forked from https://github.com/wb/gitall ) to which I contributed quite a bit some years ago.  I don't use it much these days (no real need for multi-repo operations in my new job), so there might be better things out there, but it is a very good place to start.

It is, at the least, much more versatile than hgall, as it allows arbitrary git operations, and not just those preconfigured in the script. I even added a --raw feature that will allow you to run non-git commands on all git repo subfolders.
Cheers, Jan

**Comment by svspire** [comment]
Looks like the wb version is slightly more current, so I'll fork that one. Thanks!
-SS

**Pull request merged**
